nav:
  - MainPage:
      - index.md
      - about.md
      - chronicle.md
  - Blog:
      - blog/index.md
  - SkyHigh:
      - nya/index.md
      - Outlook:
          - nya/stoic.md
      - TimeLine:
          - nya/24-a.md
          - nya/24-b.md
  - Project:
      - proj/index.md

site_name: SkyHigh
site_author: SkyHigh
site_url: https://skyhigh.moe/
repo_url: https://github.com/SkyHighR/SkyBlog
repo_name: SkyHigh'Blog
extra:
  homepage: https://skyhigh.moe
  social:
    - icon: simple/codementor
      link: https://mypic.skyhigh.moe/picv/nana.mp4

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/l.svg
  language: zh-TW
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - announce.dismiss
    - content.code.copy
    # - navigation.instant
    - navigation.instant.progress
    - navigation.prune

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      type: custom
      custom_format: "%H:%M %a %d %b %Y"
      timezone: Asia/Shanghai
      exclude:
        - blog/*
      enable_creation_date: true
  - search:
      lang:
        - zh
        - zh-TW
        - en
        - ja
  - blog:
      enabled: true
      blog_toc: true
      post_readtime: true
      post_readtime_words_per_minute: 200
      post_excerpt: optional
      post_excerpt_separator: <!-- uptoc -->
      pagination: true
      pagination_per_page: 9
      archive_date_format: yyyy
      post_date_format: full
      post_url_format: "{slug}"
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
