nav:
  - Welcome: index.md
  - Blog:
      - blog/index.md
  - DailyStoic:
      - stoic/index.md
      - 一周目:
          - stoic/0001/m01.md
          - stoic/0001/m02.md
          - stoic/0001/m03.md
          - stoic/0001/m04.md
          - stoic/0001/m05.md
          - stoic/0001/m06.md
          - stoic/0001/m07.md
          - stoic/0001/m08.md
          - stoic/0001/m09.md
          - stoic/0001/m10.md
          - stoic/0001/m11.md
          - stoic/0001/m12.md
          - stoic/0001/m13.md
      - Archive:
          - stoic/archive.md
  - Times:
      - 1704556800.md
      - kon.md

site_name: SkyHigh
site_author: SkyHigh
site_url: https://blog.skyhigh.moe/

theme:
  name: material
  # custom_dir: overrides
  font:
    text: Noto Sans SC
    code: Noto Sans SC
  favicon: img/favicon.ico
  logo: img/l.svg
  language: zh-TW
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - announce.dismiss
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  homepage: https://blog.skyhigh.moe

copyright: 2019-2024 SkyHigh; CC BY-NC 4.0
extra:
  social:
    - icon: fontawesome/brands/square-github
      link: https://github.com/SkyHighR
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/moeSkyHigh
    - icon: fontawesome/solid/envelope
      link: mailto:<hi@skyhigh.moe>

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang:
        - zh
        - en
        - ja
  - blog:
      enabled: true
      blog_toc: true
      post_readtime: true
      post_readtime_words_per_minute: 322
      post_excerpt: optional
      post_excerpt_separator: <!-- uptoc -->
      pagination: true
      pagination_per_page: 9
      archive_date_format: yyyy
      post_date_format: full
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
