site_name: SkyHigh'Blog
site_author: SkyHigh
site_url: https://blog.skyhigh.moe/

nav:
  - Welcome: index.md
  - Blog:
      - blog/index.md
  #  - Sky:
  #      SkyHihg:
  #         - p0/3.md

  - About: about.md
  - Chronicle: 1704556800.md

theme:
  name: material
  custom_dir: overrides
  font:
    text: Noto Sans SC
    code: Ubuntu
  favicon: img/favicon.ico
  logo: img/l.png
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
    - search.share
    - announce.dismiss
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  homepage: https://blog.skyhigh.moe

copyright: Copyright &copy; 2016-2024 SkyHigh
extra:
  social:
    - icon: fontawesome/brands/square-github
      link: https://github.com/SkyHighR
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/moeSkyHigh
    - icon: fontawesome/solid/envelope
      link: mailto:<hi@skyhigh.moe>
    - icon: fontawesome/brands/telegram
      link: https://t.me/moeSkyHigh

plugins:
  - search:
      lang:
        - zh
        - en
        - ja
  - blog:
      enabled: true
      blog_toc: true
      post_readtime: true
      post_readtime_words_per_minute: 322
      post_excerpt: optional
      post_excerpt_separator: <!-- uptoc -->
      pagination: true
      pagination_per_page: 9
      archive_date_format: MMMM yyyy
      post_date_format: full
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
